#!/bin/sh

# cope with both systemd and upstart
if  ps -p1 | grep systemd > /dev/null; then
  systemctl enable prometheus-node_exporter.service
  systemctl restart prometheus-node_exporter
else 
  start prometheus-node_exporter
fi
