#!/bin/sh

# create directory for textfile collector
DIR=/var/lib/prometheus-node-exporter
if ! [ -d "$DIR" ]; then
  mkdir -p "$DIR"
  chmod 1777 "$DIR"
fi

# cope with both systemd and upstart
if [ -x /bin/systemd ]; then
  systemctl daemon-reload
  systemctl enable prometheus-node_exporter.service
  systemctl restart prometheus-node_exporter
else 
  stop prometheus-node_exporter || true
  start prometheus-node_exporter
fi
